// core/services/pdf_export_service.dart
import 'dart:io';
import 'dart:ui';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../../data/models/export_model.dart';
import '../../data/models/expense_model.dart';
import '../../data/models/income_model.dart';

class PdfExportService {
  static final _currencyFmt =
  NumberFormat.currency(symbol: '\$', decimalDigits: 2);
  static final _dateFmt = DateFormat('dd MMM yyyy');

  // ── Public entry point ────────────────────────────────────────────────────

  Future<void> exportAndShare(ExportRequest request, {Rect? sharePositionOrigin}) async {
    final pdf = _buildPdf(request);
    final bytes = await pdf.save();

    final dir = await getTemporaryDirectory();
    final fileName =
        'budgeto_${_fileDateRange(request.startDate, request.endDate)}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'Budgeto Report — ${_fileDateRange(request.startDate, request.endDate)}',
      sharePositionOrigin: sharePositionOrigin,
    );
  }

  // ── PDF builder ───────────────────────────────────────────────────────────

  pw.Document _buildPdf(ExportRequest request) {
    final pdf = pw.Document();

    // ---- Colours ----
    const primary = PdfColor.fromInt(0xFF6C63FF);
    const income = PdfColor.fromInt(0xFF4CAF50);
    const expense = PdfColor.fromInt(0xFFF44336);
    const surface = PdfColor.fromInt(0xFFF5F5F5);
    const textDark = PdfColor.fromInt(0xFF1A1A2E);
    const textGrey = PdfColor.fromInt(0xFF9E9E9E);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (_) => _header(request, primary, textDark, textGrey),
        footer: (ctx) => _footer(ctx, textGrey),
        build: (ctx) => [
          pw.SizedBox(height: 24),
          _summaryRow(request, primary, income, expense, surface),
          pw.SizedBox(height: 24),
          if (request.expenses.isNotEmpty) ...[
            _sectionTitle('Expenses', expense),
            pw.SizedBox(height: 8),
            _expenseTable(request.expenses, surface, expense, textGrey),
            pw.SizedBox(height: 24),
          ],
          if (request.income.isNotEmpty) ...[
            _sectionTitle('Income', income),
            pw.SizedBox(height: 8),
            _incomeTable(request.income, surface, income, textGrey),
          ],
        ],
      ),
    );

    return pdf;
  }

  // ── Header ────────────────────────────────────────────────────────────────

  pw.Widget _header(
      ExportRequest request,
      PdfColor primary,
      PdfColor textDark,
      PdfColor textGrey,
      ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'BUDGETO',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: primary,
                  ),
                ),
                pw.Text(
                  'Financial Report',
                  style: pw.TextStyle(fontSize: 12, color: textGrey),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  request.userName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: textDark,
                  ),
                ),
                pw.Text(
                  request.userEmail,
                  style: pw.TextStyle(fontSize: 10, color: textGrey),
                ),
                pw.Text(
                  '${_dateFmt.format(request.startDate)} – ${_dateFmt.format(request.endDate)}',
                  style: pw.TextStyle(fontSize: 10, color: textGrey),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: primary, thickness: 2),
      ],
    );
  }

  // ── Footer ────────────────────────────────────────────────────────────────

  pw.Widget _footer(pw.Context ctx, PdfColor textGrey) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by Budgeto on ${_dateFmt.format(DateTime.now())}',
          style: pw.TextStyle(fontSize: 9, color: textGrey),
        ),
        pw.Text(
          'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
          style: pw.TextStyle(fontSize: 9, color: textGrey),
        ),
      ],
    );
  }

  // ── Summary row ───────────────────────────────────────────────────────────

  pw.Widget _summaryRow(
      ExportRequest request,
      PdfColor primary,
      PdfColor income,
      PdfColor expense,
      PdfColor surface,
      ) {
    return pw.Row(
      children: [
        _summaryCard('Total Income', request.totalIncome, income, surface),
        pw.SizedBox(width: 12),
        _summaryCard('Total Expenses', request.totalExpenses, expense, surface),
        pw.SizedBox(width: 12),
        _summaryCard('Net Balance', request.netBalance, primary, surface),
      ],
    );
  }

  pw.Widget _summaryCard(
      String label, double value, PdfColor color, PdfColor surface) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: surface,
          borderRadius: pw.BorderRadius.circular(8),
          border: pw.Border.all(color: color, width: 1.5),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label,
                style: pw.TextStyle(fontSize: 9, color: color)),
            pw.SizedBox(height: 4),
            pw.Text(
              _currencyFmt.format(value),
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Section title ─────────────────────────────────────────────────────────

  pw.Widget _sectionTitle(String title, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: pw.BoxDecoration(
        color: color,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  // ── Expense table ─────────────────────────────────────────────────────────

  pw.Widget _expenseTable(
      List<ExpenseModel> expenses,
      PdfColor surface,
      PdfColor accentColor,
      PdfColor textGrey,
      ) {
    return pw.Table(
      border: pw.TableBorder.all(color: surface, width: 1),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(3),
        3: const pw.FlexColumnWidth(2),
      },
      children: [
        // Header row
        pw.TableRow(
          decoration: pw.BoxDecoration(color: accentColor),
          children: ['Date', 'Category', 'Note', 'Amount']
              .map((h) => _tableHeader(h))
              .toList(),
        ),
        // Data rows
        ...expenses.asMap().entries.map((entry) {
          final i = entry.key;
          final e = entry.value;
          final bg =
          i.isEven ? PdfColors.white : surface;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: bg),
            children: [
              _tableCell(_dateFmt.format(e.date), textGrey),
              _tableCell(e.category, textGrey),
              _tableCell(
                  e.note.isNotEmpty ? e.note : '—', textGrey),
              _tableCellRight(
                  _currencyFmt.format(e.amount), accentColor),
            ],
          );
        }),
        // Total row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.white),
          children: [
            _tableCell('', textGrey),
            _tableCell('', textGrey),
            _tableCellBold('Total', textGrey),
            _tableCellRight(
              _currencyFmt.format(
                  expenses.fold(0.0, (s, e) => s + e.amount)),
              accentColor,
            ),
          ],
        ),
      ],
    );
  }

  // ── Income table ──────────────────────────────────────────────────────────

  pw.Widget _incomeTable(
      List<IncomeModel> incomes,
      PdfColor surface,
      PdfColor accentColor,
      PdfColor textGrey,
      ) {
    return pw.Table(
      border: pw.TableBorder.all(color: surface, width: 1),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(3),
        3: const pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: accentColor),
          children: ['Date', 'Source', 'Note', 'Amount']
              .map((h) => _tableHeader(h))
              .toList(),
        ),
        ...incomes.asMap().entries.map((entry) {
          final i = entry.key;
          final inc = entry.value;
          final bg = i.isEven ? PdfColors.white : surface;
          return pw.TableRow(
            decoration: pw.BoxDecoration(color: bg),
            children: [
              _tableCell(_dateFmt.format(inc.date), textGrey),
              _tableCell(inc.source, textGrey),
              _tableCell(
                  inc.note.isNotEmpty ? inc.note : '—', textGrey),
              _tableCellRight(
                  _currencyFmt.format(inc.amount), accentColor),
            ],
          );
        }),
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.white),
          children: [
            _tableCell('', textGrey),
            _tableCell('', textGrey),
            _tableCellBold('Total', textGrey),
            _tableCellRight(
              _currencyFmt.format(
                  incomes.fold(0.0, (s, i) => s + i.amount)),
              accentColor,
            ),
          ],
        ),
      ],
    );
  }

  // ── Table cell helpers ────────────────────────────────────────────────────

  pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  pw.Widget _tableCell(String text, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      child: pw.Text(text,
          style: pw.TextStyle(fontSize: 9, color: color)),
    );
  }

  pw.Widget _tableCellRight(String text, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      child: pw.Text(
        text,
        textAlign: pw.TextAlign.right,
        style:
        pw.TextStyle(fontSize: 9, color: color, fontWeight: pw.FontWeight.bold),
      ),
    );
  }

  pw.Widget _tableCellBold(String text, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      child: pw.Text(
        text,
        style: pw.TextStyle(
            fontSize: 9,
            fontWeight: pw.FontWeight.bold,
            color: color),
      ),
    );
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  String _fileDateRange(DateTime start, DateTime end) {
    final fmt = DateFormat('yyyyMMdd');
    return '${fmt.format(start)}_${fmt.format(end)}';
  }
}